# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56590c53eaeab9904c1015ad99dc77c2c01f77b38f9d87a7bed611b326ca6860a21440570eb90c7f04ecf8003b17886cc2418532d9ca8b56b047b957c7494249

test:
  secret_key_base: 632791820bd3ca2cd054fd4e75d96863b157896a15cda60d0d0ef4642608243b6a2dcb5d33730677e556b0ac9dff803e64714ac7e9cf595c057d2a8816b7e268

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
